name: ModernWeapons
version: 1.3.1
description: A small weapons plugin
author: DarkBlade12
api-version: 1.19
website: http://dev.bukkit.org/profiles/DarkBladee12
main: com.DarkBlade12.ModernWeapons.ModernWeapons
depend: [WorldEdit, WorldGuard]
commands:
  mw:
    usage: See the devbukkit page for command information
    description: General ModernWeapons command
    aliases: [mwe, mweapons, modernweapons]